OBJS = main.o common.o
all: sample

sample:  $(OBJS)
	gcc -o sample $(OBJS)

# only dependencies are listed here
main.o: common.h
common.o: common.h

# clean removes all object files but leaves the executable
clean:
	rm -f $(OBJS)
